openproximity2/django-web/openproximity/urls.py
#    OpenProximity2.0 is a proximity marketing OpenSource system.
#    Copyright (C) 2010,2009,2008 Naranjo Manuel Francisco <manuel@aircable.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation version 2 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
from django.conf.urls.defaults import *
from django.views.generic import list_detail
from django import forms
from django.contrib.auth.decorators import login_required
import django.contrib.databrowse as databrowse
from django.contrib.databrowse.datastructures import EasyModel
from django.views.generic.simple import direct_to_template

from models import *
import views
import treeview

class RemoteRecordForm(forms.ModelForm):
    class Meta:
        model = DeviceRecord
    
databrowse_root = databrowse.DatabrowseSite()
databrowse_root.register(BluetoothDongle)
databrowse_root.register(ScannerBluetoothDongle)
databrowse_root.register(RemoteScannerBluetoothDongle)
databrowse_root.register(RemoteDevice)
databrowse_root.register(RemoteBluetoothDeviceFoundRecord)
databrowse_root.register(RemoteBluetoothDeviceFileTry)
databrowse_root.register(RemoteBluetoothDeviceFilesSuccess)
databrowse_root.register(RemoteBluetoothDeviceFilesRejected)
databrowse_root.register(MarketingCampaign)
databrowse_root.register(CampaignFile)

info_dict = {
    'form_class': RemoteRecordForm,
    'post_save_redirect': '../accepted/',
}

from microblog.sites import TweetSite
def convert(time_string):
    return datetime.strptime(time_string, '%Y-%m-%d %H:%M:%S')

blog = TweetSite(LogLine, 'time', convert)

urlpatterns = patterns('',
    (r'^accepted/$', views.add_record_accepted),
    (r'^genericadd/$', 'django.views.generic.create_update.create_object', info_dict),
    (r'^remoteadd/$', views.add_record),
    (r'^data/(.*)$', databrowse_root.root ),
    (r'^rpc/server/(?P<command>.+)', views.server_rpc_command),
    (r'^rpc/(?P<command>.+)', views.rpc_command),
    (r'^configure/dongle/(?P<address>.+)', views.configure_dongle),
    (r'^configure/dongle/', views.configure_dongle),
    (r'^configure/camp/(?P<camp_name>.+)', views.configure_campaign),
    (r'^configure/camp/', views.configure_campaign),
    (r'^stats/restart.*', views.stats_restart),
    (r'^file/grab/(?P<file>.+)', views.grab_file),
    (r'^microblog/', include(blog.urlpatterns)),
    (r'^last-seen/$', views.last_seen),
    (r'^treeview/', include(treeview.urlpatterns)),
    (r'^$', views.index),
)

openproximity2/django-web/urls.py
#    OpenProximity2.0 is a proximity marketing OpenSource system.
#    Copyright (C) 2010,2009,2008 Naranjo Manuel Francisco <manuel@aircable.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation version 2 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from net.aircable.utils import getLogger
logger = getLogger(__name__)

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

import os

from net.aircable.openproximity.pluginsystem import pluginsystem

admin.autodiscover()

urlpatterns = patterns ('',
    (r'^accounts/$', login, {'template_name': 'op/login.html'}),
    (r'^accounts/login', login, {'template_name': 'op/login.html'}),
    (r'^accounts/', include('django.contrib.auth.urls')),

    # include needed interfaces    
#    (r'^bluez/', include('bluez.urls')),
    (r'^openproximity/', include('openproximity.urls')),
    
    #include translation site
    (r'^admin/translate/', include('rosetta.urls'),{},"translate"),
    
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
#    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls),{},"admin"),
    
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
        {       'document_root': os.path.join(os.path.dirname(__file__), 'media')},
        "site-media"
    ),
    
    (r'^notification/', include('notification.urls'),{},"notification"),
)

for plugin in pluginsystem.get_plugins('urls'):
    logger.info("%s provides urls" % plugin.provides.get('name', plugin.name))
    url, path = plugin.provides.get('urls')
    urlpatterns += patterns( '', 
        (r'^%s/' % url, 
            include('%s.%s' % ( plugin.name, path)),
            {},
            plugin.name # allow url to be reverse resolved
    ))

urlpatterns += patterns('', 
    (r'', include('openproximity.urls'),{},"openproximity")
)

urlpatterns += staticfiles_urlpatterns()

openproximity2/django-web/openproximity/models.py
# -*- coding: utf-8 -*-
# OpenProximity2.0 is a proximity marketing OpenSource system.
# Copyright (C) 2010,2009,2008 Naranjo Manuel Francisco <manuel@aircable.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
from datetime import datetime
import time

from pickle import dumps, loads
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext as _
from django.dispatch.dispatcher import Signal
from django.contrib.auth.models import User
from timezones.fields import TimeZoneField

import rpyc, time, os.path

import net.aircable.openproximity.signals.scanner as scanner

from net.aircable.fields import PickledField
from net.aircable.utils import getLogger
logger = getLogger(__name__)

from openproximity.rpc.dispatcher import Dispatcher

import errno

TIMEOUT_RET = [
    errno.ENOTCONN, # 107
]

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    timezone = TimeZoneField()

class LogLine(models.Model):
    time = models.DateTimeField(auto_now=True, verbose_name=_("time"))
    content = models.CharField(max_length=255)

class Setting(models.Model):
    name = models.CharField(max_length=40)
    value = PickledField(max_length=200)

class BluetoothDongle(models.Model):
    address = models.CharField(
        max_length=17, 
        blank=False, 
        verbose_name=_("bluetooth address")
    )
    name = models.CharField(
        max_length=100, 
        blank=True,
        verbose_name=_("identifying name")
    )
    enabled = models.BooleanField()

    def enabled_display(self):
        if self.enabled:
            return "Enabled"
        return "Disabled"
    
    def __unicode__(self):
        return "%s - %s, %s" % (
            self.address, 
            self.name, 
            self.enabled_display() 
        )

class ScannerBluetoothDongle(BluetoothDongle):
    priority = models.IntegerField()

    def __unicode__(self):
        return "Scanner: %s, %s" % (
            BluetoothDongle.__unicode__(self), 
            self.priority
        )

class RemoteScannerBluetoothDongle(ScannerBluetoothDongle):
    local_dongle = models.ForeignKey(
        ScannerBluetoothDongle, 
        related_name="remote_dongles" )

class UploaderBluetoothDongle(BluetoothDongle):
    max_conn = models.IntegerField(
        default=7,
        verbose_name=_("connections"),
        help_text=_("maximum allowed connections")
    )
    
    def __unicode__(self):
        return "Uploader: %s, %s" % (
            BluetoothDongle.__unicode__(self), 
            self.max_conn
        )

SERVICE_TYPES = (
    (0,   u'opp'),
    (1,   u'ftp'),
)

class Campaign(models.Model):

    #name is going to change
    name = models.CharField(
        max_length=100,
        verbose_name=_("campaign name")
    )
    enabled = models.BooleanField(
        default=True,
        verbose_name=_("campaign enabled")
    )
    name_filter = models.CharField(
        null=True,
        max_length=30,
        blank=True,
        verbose_name=_("name filter")
    )
    addr_filter = models.CharField(
        null=True, 
        max_length=20, 
        blank=True,
        verbose_name=_("address filter")
    )
    devclass_filter = models.IntegerField(
        null=True, 
        blank=True,
        verbose_name=_("devclass filter")
    )
    start = models.DateTimeField(
        null=True, 
        blank=True,
        help_text=_("starting date, or null to run for ever until end"),
        verbose_name=_("start date")
    )
    end = models.DateTimeField(
        null=True, 
        blank=True,
        help_text=_("ending date, or null to run for ever since start"),
        verbose_name=_("end date")
    )
    dongle_name=models.CharField(
        null=True, 
        blank=True, 
        max_length=100,
        verbose_name=_("dongles names"),
        help_text=_("if you want your campaign to change "
        "the bluetooth dongles names when running then "
        "set this variable"),
    )
    pin_code=models.CharField(
        null=True, 
        blank=True, 
        max_length=16,
        default="1234",
        help_text=_("certain target devices require pairing"
            ", this is the pin code going to be used"),
        verbose_name=_("PIN code")
    )
    concurrent_scanning=models.BooleanField(
        default=False,
        help_text=_("concurrent scanning makes all your "
            "scanners to run simultaneous, instead of doing so in a "
            "sequence one after the other, if you enable this scanner "
            "priority is ignored"),
        verbose_name=_("concurrent scanning")
    )


    def matches(self, remote, *args, **kwargs):
        return False

    def __unicode__(self):
        return self.name

    class Meta:
        # don't create a table for me please
        abstract = True
        ordering = ['start', 'end', 'name']

class MarketingCampaign(Campaign):
    service = models.IntegerField(default=0, choices=SERVICE_TYPES)
    rejected_count = models.IntegerField(
        default=2,
        help_text=_("how many times it should try again when rejected, -1 "
            "infinite"),
        verbose_name=_("rejected count")
    )
    rejected_timeout = models.IntegerField(
        default=-1,
        help_text=_("how much time to wait after a certain "
        "device has rejected a file before we "
        "try again"),
        verbose_name=_("rejected timeout")
    )
    tries_count = models.IntegerField(
        default=-1,
        help_text=_("how many times it should try to send "
        "when timing out, -1 infinite"),
        verbose_name=_("tries count")
    )
    tries_timeout = models.IntegerField(
        default=0,
        help_text=_("how much time to wait after a certain "
        "device has made a timeout before we try again"),
        verbose_name=_("tries timeout")
    )
    accepted_count = models.IntegerField(
        default=-1,
        help_text=_("how many times will this campaign be "
        "accepted before disabling, -1 means infinite"),
        verbose_name=_("accepted count")
    )
    rssi_min = models.IntegerField(
        null=True, 
        blank=True,
        help_text=_("if the meassured rssi is over or equal"
        " than this value then campaign will match, "
        "take into account rssi is negative, range -255 "
        "0"),
        verbose_name=_("RSSI min")
    )
    rssi_max = models.IntegerField(
        null=True, 
        blank=True,
        help_text=_("if the meassured rssi is less or equal"
        " than this value then campaign will match, "
        "take into account rssi is negative, range -255"
        " 0"),
        verbose_name=_("RSSI max")
    )
    fixed_channel=models.IntegerField(
        null=True,
        blank=True,
        default = None,
        help_text=_("if you set this parameter then "
        "OpenProximity will never try to resolve sdp records and "
        "use only this channel, leave it empty unless you know "
        "what you're doing."),
        verbose_name=_("fixed channel")
    )
    upload_on_discovered = models.BooleanField(
        default=False,
        help_text=_("in some cases you may want to force "
            "that the same dongle that discovers a device is "
            "the one that's going to do the upload. Make sure "
            "all your dongles can work as scanner and uploaders "
            "otherwise you will not service some devices."),
        verbose_name=_("scan and upload on same dongle")
    )


    def __unicode__(self):
        return "MarketingCampaign: %s" % self.name

    def getTimeoutCount(self, remote):
        ''' this function will count how many times a certain devices did a
            timeout
        '''
        return RemoteBluetoothDeviceFilesRejected.objects.\
            filter(remote=remote, campaign=self).\
            filter(ret_value__in=TIMEOUT_RET).count()

    def getRejectedCount(self, remote):
        ''' this function will count how many time the user has rejected'''
        return RemoteBluetoothDeviceFilesRejected.objects.\
            filter(remote=remote, campaign=self).\
            exclude(ret_value__in=TIMEOUT_RET).count()

    def getTriesCount(self, remote):
        return RemoteBluetoothDeviceFileTry.\
            objects.filter(remote=remote, campaign=self).count()

    def hasAccepted(self, remote):
        return RemoteBluetoothDeviceFilesSuccess.objects.filter(
            campaign=self, remote=remote).count()>0

    def getAcceptedCount(self):
        return RemoteBluetoothDeviceFilesSuccess.\
            objects.filter(campaign=self).count()

    
    def __getRecordForRemote(self, remote):
        '''
        Internal method used to recover the record needed to match
        the given campaign, when trying to determinate if we should try
        again or not on this device.
        '''
        pair_tries = RemoteBluetoothDevicePairing.objects.filter(
            remote=remote.address).order_by('-time')[:1]
        file_tries = RemoteBluetoothDeviceFilesRejected.objects.filter(
            campaign=self, remote=remote).order_by('-time')[:1]
        if pair_tries.count() == 0 and files_tries.count() == 0:
            return None
        if pair_tries.count() == 0:
            return files_tries[0]
        if files_tries.count() == 0:
            return pair_tries[0]
        

openproximity2/django-web/openproximity/templates/op/imports/campaigns.html
{% load i18n openproximity %}
<div class="campaigns">
    <fieldset>
        <legend>{% trans "Marketing Campaigns" %}</legend>
        {% for camp in camps %}
        <fieldset>
            <div class="setting">
                <div class="label">{% trans "Name" %}</div>
                <span class="value">
                    <a href="admin/openproximity/marketingcampaign/{{camp.pk}}/" >{{ camp.name }}</a>
                </span>
            </div>
            <div class="setting">
                <div class="label">{% trans "Enabled" %}</div>
                <span class="value">{{ camp.enabled|yesno:_("yes,no") }}</span>
            </div>
            <div class="setting">
                <div class="label">{% trans "Service" %}</div>
                <span class="value">{{ camp.get_service_display|default:"NA"}}</span>
            </div>
            <div class="setting">
                <div class="label">{% trans "Start" %}</div>
                <span class="value">{{ camp.start|default:_("Not Set") }}</span>
            </div>
            <div class="setting">
                <div class="label">{% trans "End" %}</div>
                <span class="value">{{ camp.end|default:_("Not Set") }}</span>
            </div>
            <div class="setting">
                <div class="label">{% trans "Name Filter" %}</div>
                <span class="value">{{ camp.name_filter|default:_("Not Set") }}</span>
            </div>
            <div class="setting">
                <div class="label">{% trans "Address Filter" %}</div>
                <span class="value">{{ camp.addr_filter|default:_("Not Set") }}</span>
            </div>
            <div class="setting">
                <div class="label">{% trans "DevClass Filter" %}</div>
                <span class="value">{{ camp.devclass_filter|default:_("Not Set") }}</span>
            </div>
            {% for file in camp.campaignfile_set.all %}
                <div class="setting">
                    <div class="label">{% trans "Serving File" %}</div>
                    <span class="value">{{ file.file.name|default:_("Not Set") }}</span>
                </div>
                <div class="setting">
                    <div class="label">{% trans "Chances" %}</div>
                    <span class="value">{{ file.chance|default:_("Not Set") }}</span>
                </div>
                {% createNavButton "file/grab/{{file.file.name}}" "campaign_file_{{file.id}}" _("See File") "width: 20em; color: #E4E4E4" %}
            {% empty %}
                <div class="setting">
                    <span class="value">
                        <strong>{% trans "This campaign doesn't provide any files" %}</strong>
                    </span>
                </div>
            {% endfor %}
        </fieldset>
        {% empty %}
            <strong>{% trans "There are none known campaigns" %}:</strong>
            <a href="/admin/openproximity/marketingcampaign/add/">{% trans "Create a campaign Now" %}</a>
        {% endfor %} <!-- camps -->
    </fieldset>
</div>

openproximity2/django-web/openproximity/templates/op/imports/known_dongles.html
{% load i18n %}
<div class="dongles">
    <h1>{% trans "Known Dongles" %}</h1>
    <div class="rounded-white known">
    <table id="known" class="known" style="width:100%">
        <thead>
            <tr>
            <td>{% trans "Address" %}</td>
            <td>{% trans "Is Scanner" %}</td>
            <td>{% trans "Scanner Enabled" %}</td>
            <td>{% trans "Scanner Priority" %}</td>
            <td>{% trans "Is Uploader" %}</td>
            <td>{% trans "Uploader Enabled" %}</td>
            <td>{% trans "Max Connections" %}</td>
            <td></td>
            </tr>
        </thead>
        <tbody>
            <tr><td></td></tr>
        </tbody>
    </table>
    </div>
</div>

openproximity2/django-web/openproximity/templates/op/imports/plugins.html
{% load i18n openproximity %}
{% plugins %}

{% if plugins %}
    <li class="plugins">
        <span>{% trans "Plugins" %}</span>

	    <select style="border: none" onchange="window.location.href=this.value" id="plugins_list">
        	<option value="/">----------------------</option>
            	{% for plugin in plugins %}
        		<option value="/{{ plugin.provides.urls.0 }}/" >{{ plugin.name }}</option>
            	{% endfor %}
	    </select>
    </li>
{% endif %}

openproximity2/django-web/openproximity/templates/op/imports/server_stats.html
{% load i18n openproximity %}
<div class="stats">
    <fieldset>
        <legend>{% trans "Server Statistics" %}</legend>
        <div class="setting">
            <div class="label">{% trans "Seen" %}</div>
            <span class="value" id="stats_seen">{{ stats.seen.total }}</span>
        </div>
        <div class="setting">
            <fieldset>
                <legend>{% trans "Per Dongle" %}</legend>
                {% for d in stats.seen.perdongle %}
                    <div class="setting">
                        <div class="label">{{ d.address}}</div>
                        <span class="value" id="stats_count_{{ d.address }}">{{ d.count }}</span>
                    </div>
                {% endfor %}
            </fieldset>
        </div>
        <div class="setting">
            <div class="label">{% trans "Valid Obex" %}</div>
            <span class="value" id="stats_valid">{{ stats.valid }}</span>
        </div>
        <div class="setting">
            <div class="label">{% trans "Tried" %}</div>
            <span class="value" id="stats_tries">{{ stats.tries }}</span>
        </div>
        <div class="setting">
            <div class="label">{% trans "Timeout" %}</div>
            <span class="value" id="stats_timeout">{{ stats.timeout }}</span>
        </div>
        <div class="setting">
            <div class="label">{% trans "Rejected" %}</div>
            <span class="value" id="stats_rejected">{{ stats.rejected }}</span>
        </div>
        <div class="setting">
            <div class="label">{% trans "Accepted" %}</div>
            <span class="value" id="stats_accepted">{{ stats.accepted }}</span>
        </div>
        {% if stats.error %}
            <div class="setting error" id="error">
                <div class="label">{% trans "Error Message" %}</div>
                <span class="value">{{ stats.error }}</span>
            </div>
        {% endif %}
        <div class="button corners" id="reset-stats" onclick="reset_stats();">
            {% trans "Reset Statistics" %}
        </div>

    </div>
    </fieldset>
</div>

openproximity2/django-web/openproximity/templates/op/imports/server_status.html
{% load i18n %}
<div class="server" id="rpc">
    <fieldset>
        <legend>{% trans "Server Status" %}</legend>
        <div class="setting">
            <div class="label">{% trans "RPC Server is running" %}</div>
            <span class="value" id="rpc_running">{{ rpc.running|yesno:_("yes,no") }}</span>
        </div>
        <div class="setting">
            <div class="label">{% trans "Uploaders Connected" %}</div>
            <span class="value" id="rpc_uploadres">{{ rpc.uploaders }}</span>
        </div>
        <div class="setting">
            <div class="label">{% trans "Scanners Connected" %}</div>
            <span class="value" id="rpc_scanners">{{ rpc.scanners }}</span>
        </div>
        {% if rpc.error %}
            <div class="setting error" id="error">
                <div class="label">{% trans "Error Message" %}</div>
                <span class="value" id="error">{{ rpc.error }}</span>
            </div>
        {% endif %}
        <div class="button corners" id="reset-server" onclick="reset_server();">
            {% trans "Reset RPC Server" %}
        </div>
    </fieldset>
</div>

openproximity2/django-web/openproximity/templates/op/imports/userinfo.html
{% load i18n %}

{% if user.is_authenticated %}
    <li class="username">
        <span>{% trans 'Welcome,' %} <strong>{% firstof user.first_name user.username %}</strong></span>
    </li>
    <li>
        <a href="/accounts/password_change">{% trans "Change password" %}</a>
    </li>
    <li>
        <a href="/accounts/logout">{% trans "Log out" %}</a>
    </li>
{% else %}
    <li class="username">
        <span>{% trans 'Welcome,' %} <strong>{% trans 'Anonymous' %}</strong></span>
    </li>
    <li>
        <a href="/accounts/login/">{% trans "Log in" %}</a>
    </li>
{% endif %}